"""Generate `gettsim_input_scope.json`: the in-scope GETTSIM qnames per policy period.

Run offline from an environment where `gettsim` is importable (the dev-gettsim workspace
root), never at runtime — `soep-preparation` carries no GETTSIM dependency. GETTSIM is
imported dynamically so the static type checker in the soep environment (which has no
GETTSIM) does not try to resolve it.

For every policy-date boundary in GETTSIM's objects, the script reads which
`BASE_MAPPING` qnames are part of GETTSIM's policy environment at that date, then
collapses adjacent
boundaries whose in-scope set is identical into one period. Coverage runs from the start
of the SOEP survey range; periods starting before 2005 are flagged `low_confidence`
because GETTSIM's pre-2015 environments are incomplete (gettsim issue #962).

Usage (from the workspace root):

    pixi run -e py314 python \
        soep-preparation/src/soep_preparation/gettsim_inputs/_generate_input_scope.py
"""

import datetime
import importlib
import json
from pathlib import Path
from typing import Any

from soep_preparation.gettsim_inputs.mapping import BASE_MAPPING

SCOPE_PATH = Path(__file__).with_name("gettsim_input_scope.json")
# GETTSIM rules carry a far-future default end of 2099-12-31; covering past it would add
# a spurious tail period in which every dated rule has expired.
_FIRST_COVERED_DATE = datetime.date(1984, 1, 1)
_LAST_COVERED_DATE = datetime.date(2099, 12, 31)
_LOW_CONFIDENCE_BEFORE = datetime.date(2005, 1, 1)


def _gettsim_boundary_dates() -> list[datetime.date]:
    """Return the sorted policy-date boundaries of GETTSIM's column objects."""
    gettsim = importlib.import_module("gettsim")
    main, main_target = gettsim.main, gettsim.MainTarget
    objects = main(
        main_target=main_target.orig_policy_objects.column_objects_and_param_functions,
    )
    boundaries: set[datetime.date] = set()
    for obj in objects.values():
        boundaries.add(obj.start_date)
        boundaries.add(obj.end_date + datetime.timedelta(days=1))
    cuts = {
        date for date in boundaries if _FIRST_COVERED_DATE < date <= _LAST_COVERED_DATE
    }
    cuts.add(_FIRST_COVERED_DATE)
    return sorted(cuts)


def _in_scope_at(policy_date: datetime.date) -> frozenset[str]:
    """Return the `BASE_MAPPING` qnames in GETTSIM's environment at `policy_date`."""
    gettsim = importlib.import_module("gettsim")
    main, main_target = gettsim.main, gettsim.MainTarget
    all_qnames = set(
        main(
            main_target=main_target.labels.all_qnames_in_policy_environment,
            policy_date_str=policy_date.isoformat(),
        )
    )
    return frozenset(qname for qname in BASE_MAPPING if qname in all_qnames)


def build_periods() -> list[dict[str, Any]]:
    """Build the collapsed list of policy periods with their in-scope qnames."""
    cuts = _gettsim_boundary_dates()
    ends = [*(cut - datetime.timedelta(days=1) for cut in cuts[1:]), _LAST_COVERED_DATE]

    periods: list[dict[str, Any]] = []
    for start, end in zip(cuts, ends, strict=True):
        in_scope = _in_scope_at(start)
        if periods and frozenset(periods[-1]["in_scope"]) == in_scope:
            periods[-1]["end_date"] = end.isoformat()
            continue
        periods.append(
            {
                "start_date": start.isoformat(),
                "end_date": end.isoformat(),
                "low_confidence": start < _LOW_CONFIDENCE_BEFORE,
                "in_scope": sorted(in_scope),
            }
        )
    return periods


def write_scope_file(path: Path = SCOPE_PATH) -> None:
    """Generate the scope file and write it as formatted JSON."""
    document = {
        "_comment": (
            "Generated by _generate_input_scope.py from GETTSIM: per policy period, "
            "the BASE_MAPPING qnames in GETTSIM's environment. Do not edit by hand."
        ),
        "n_base_qnames": len(BASE_MAPPING),
        "periods": build_periods(),
    }
    text = json.dumps(document, ensure_ascii=False, indent=2) + "\n"
    path.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    write_scope_file()
