---
name: main
# Automatically cancel a previous run.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  run-tests:
    name: Run tests for ${{ matrix.os }} on ${{ matrix.environment }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        environment:
          - py314
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: prefix-dev/setup-pixi@v0.10.1
        with:
          pixi-version: v0.76.1
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          frozen: true
          environments: ${{ matrix.environment }}
      - name: Run tests without coverage
        if: ${{ !(runner.os == 'Linux' && matrix.environment == 'py314') }}
        run: pixi run --locked -e ${{ matrix.environment }} tests
        shell: bash -el {0}
      - name: Run tests with coverage
        if: runner.os == 'Linux' && matrix.environment == 'py314'
        run: pixi run --locked -e py314 tests-with-cov
        shell: bash -el {0}
      - name: Upload coverage report
        if: runner.os == 'Linux' && matrix.environment == 'py314'
        uses: codecov/codecov-action@v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  run-ty:
    name: Run ty
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: prefix-dev/setup-pixi@v0.10.1
        with:
          pixi-version: v0.76.1
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          frozen: true
          environments: py314
      - name: Run ty
        run: pixi run --locked -e py314 prek run ty --all-files
        shell: bash -el {0}
